mysite/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),                            # blog/
    path('tag/<slug:tag_slug>/',                                            # blog/tag/标签名
         views.post_list,
         name='post_list_by_tag',
    ),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',                   # blog/年/月/日/文章名
         views.post_detail,
         name='post_detail',
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),      # blog/文章编号/share/
    path('feed/', LatestPostsFeed(), name='post_feed'),                     # blog/feed/
    path('search/', views.post_search, name='post_search'),                 # blog/search/
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap 
from django.urls import path, include

from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', 
         sitemap, 
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                                            .filter(status='published') 


class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status='draft') 


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish') 
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
        
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
# postgres 全文搜索
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    # 有标签参数，根据标签筛选文章
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # 分页器
    paginator = Paginator(object_list, 3) # 每页三篇文章 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:              # 请求页面数不是整数，返回第一页 
        posts = paginator.page(1) 
    except EmptyPage:                     # 请求页面为空，返回最后一页
        posts = paginator.page(paginator.num_pages)
    
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})

                 
# def post_list(request):
#     posts = Post.published.all()
#     return render(request,
#                   'blog/post/list.html',
#                   {'posts': posts})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # 正常评论
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':  # 收到评论表单
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # 创建评论对象，暂不写入数据库
            new_comment = comment_form.save(commit=False) 
            # 修改评论post值为当前文章
            new_comment.post = post 
            # 写入数据库
            new_comment.save() 
    else:
        comment_form = CommentForm()

    # 利用相同标签数量排序筛选最相似文章
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # 根据 id 得到文章
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':  # 分享表单提交
        form = EmailPostForm(request.POST)
        if form.is_valid():       # 表单通过验证
            cd = form.cleaned_data
            # 发送分享邮件
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends your read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']], fail_silently=False)
            sent = True
    else:
        form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})

    
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A')\
                            + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            # results = Post.published.annotate(
            #                             rank=SearchRank(search_vector, search_query)
            #                         )\
            #                         .filter(rank__gte=0.3)\
            #                         .order_by('-rank')
            results = Post.published.annotate(
                          similarity=TrigramSimilarity('title', query),)\
                                    .filter(similarity__gt=0.1)\
                                    .order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}


{% block title %}{{ post.title }}{% endblock %}


{% block content %}
    <!-- 标题 -->
    <h1>
        {{ post.title }}
    </h1>
    
    <!-- 标签 -->
    <p class="tags">
        标签：
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
            </a>
        {% if not forloop.last %}， {% endif %}
        {% endfor %}
    </p>

    <!-- 日期 -->
    <p class="date">
        日期： {{ post.publish }} 作者： {{ post.author }}
    </p>

    <!-- 正文 -->
    {{ post.body|markdown }}
    
    <!-- 分享 -->
    <p>
        <a href="{% url "blog:post_share" post.id %}"> 分享给你的朋友</a>
    </p>

    <!-- 相似文章推荐 -->
    <h2>相似的文章</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        无。
    {% endfor %}
    
    <!-- 展示评论 -->
    {% with comments.count as total_comments %}
        <h2>
            总评论数： {{ total_comments }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                评论 {{ forloop.counter }}  {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>无.</p>
    {% endfor %}

    <!-- 评论表单 -->
    {% if new_comment %}
        <h2>评论成功.</h2>
    {% else %}
        <h2>添加评论</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}


{% block title %}我的博客{% endblock %}

{% block content %}
    <h1>我的博客</h1>
    
    <!-- 标签筛选 -->
    {% if tag %}
    <h2>
        含有标签 "{{ tag.name }}" 的文章
    </h2>
    {% endif %}

    <!-- 所有文章概览 -->
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a> 
        </h2>
        <p class="tags">
            标签：
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
            {% if not forloop.last %}， {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            日期： {{ post.publish }} 作者： {{ post.author }}
        </p>
        {{ post.body|markdown|linebreaks }}
    {% endfor %}

    <!-- 分页器 -->
    {% include "blog/pagination.html" with page=posts %} 
{% endblock %}

mysite/blog/templates/blog/post/most_commented_posts.html
<ul>
    {% for post in most_commented_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }} 
        {% endwith %}
    </h3>
    {% for post in results %}
        <h4>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}
    <p>
        <a href="{% url "blog:post_search" %}">Search again</a>
    </p>
{% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
{% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post"> 
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}